# This is a config for E2B sandbox template.
# You can use template ID (hgmbd8en87y8om2hshd2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("hgmbd8en87y8om2hshd2") # Sync sandbox
# sandbox = await AsyncSandbox.create("hgmbd8en87y8om2hshd2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('hgmbd8en87y8om2hshd2')

team_id = "ee17ce53-cecb-4896-9476-94a788ce3127"
memory_mb = 4_096
cpu_count = 4
dockerfile = "Dockerfile"
template_id = "hgmbd8en87y8om2hshd2"
